import { Urbanist } from "@next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"], // Add the weights you need
  variable: "--font-urbanist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const siteUrl = "https://example.com";
  const siteName = "Example Site";
  const logoSrc = "/path-to-logo.gif";
  const menus = {
    desktop: [
      { title: "Home", url: "/" },
      { title: "About", url: "/about" },
      { title: "Contact", url: "/contact" },
    ],
    mobile: [
      { title: "Home", url: "/" },
      { title: "About", url: "/about" },
      { title: "Contact", url: "/contact" },
    ],
  };
  const socialLinks = [
    { icon: "InstagramIcon", url: "https://instagram.com" },
    { icon: "FacebookIcon", url: "https://facebook.com" },
  ];

  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
